42ity/fty-sensor-env

CMakeLists.txt
builds/valgrind/ci_build.sh
ci_build.sh
ci_deploy.sh
configure.ac
include/fty_sensor_env_library.h
project.xml

Solution: add version to project.xml
Problem: we need czmq 3.0.2
Solution: add release to project.xml
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>

Problem: version is missing

---

src/fty-sensor-env.service.in

Solution: fix a binary name in service file
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>

Problem: can't start main via systemd

---

src/fty_sensor_env.cc

Solution: don't use element_src
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>

Problem: can't build with recent fty-proto

---

src/fty_sensor_env.cc

Solution: do the subject correctly
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>

Problem: no TH values produced

---

src/fty_sensor_env.cc

Solution: set the correct time
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>

Problem: agent-th sends metrics from 1970

---

src/fty_sensor_env.cc

SOLUTION: Fix it
More details in commit message.
Note: Sorry for big PR. This should have been several smaller
commits, got distracted writing this :).

PROBLEM: RC removal and re-insertion is not supported

---

src/fty_sensor_env.cc

BIOS-3540
SOLUTION: Fix it
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>

PROBLEM: TH published even without id

---

src/fty_sensor_env.cc

When a series of asset messages is received from stream,
they are processed one at a time with a timeout equal to polling
interval of sensor reading.
SOLUTION: Fix it.
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>

PROBLEM: slow (5s) asset message process timeout

---

include/libth.h
src/fty_sensor_env.cc

Several problem definitions

---

src/fty_sensor_env.cc

Solution: subtype name corrected
Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>

Problem: sensor does not work with rack controller

---

include/fty_sensor_env.h
include/libth.h
src/fty_sensor_env.cc
src/libth.cc

Problem: EMP devices don't publish EMP's GPIs status

---

include/fty_sensor_env.h
src/fty_sensor_env.cc

Solution: added proper ASSETS support

Problem: sensor assets were ignored, sensor messages were sent based on sensor connection to serial port.

---

src/fty_sensor_env_server.c

Problem: no unit tests were available for this agent

---

src/fty_sensor_env.c
src/fty_sensor_env_server.c

Solution: fixed pipe messages, added request for assets.

Problem: agent forget to ask for assets

---

include/fty_sensor_env.h
src/fty_sensor_env.c
src/fty_sensor_env_server.c

Solution: Fixed agent stopping using global shared value set by signal handlers.

Problem: Agent occasionally gets stuck when stopped

---

README
README.md

Solution: Improve it.
Signed-off-by: Jana Rapava <janarapava@eaton.com>

Problem: README is incomplete.

---

src/fty_sensor_env_server.c

Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>

Problem : handling properly nonactive asset

---

src/fty_sensor_env_server.c

backport to 1.4 : handling properly nonactive asset 

---

include/fty_sensor_env.h
src/fty_sensor_env_server.c

Solution: added proper handling of asset manipulation
M/M

Problem: asset deletion and manipulation are not handled properly

---

src/fty_sensor_env_server.c

Solution: ignore sensors that aren't connected to rackcontroller-0

Problem: attempt to read data for sensors that are not connected to rackcontroller

---

src/fty_sensor_env_server.c

Solution: improved deleted message handling (delete message miss aux parents).
C: M, I: M

Problem: deleted sensors are still monitored
